language: python

python:
  - "2.7"

before_install:
  - pip install -U pip
  - pip install wheel

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt

script:
  - django-admin.py startproject --template=. --extension=py,md,ini my_proj
  - cd my_proj/src
  - cp my_proj/settings/local.sample.env my_proj/settings/local.env
  - python manage.py migrate
  - flake8
